export const oneDarkPro = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { background: '282c34' },
        { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c678dd' },
        { token: 'keyword.control', foreground: 'c678dd' },
        { token: 'keyword.operator', foreground: 'c678dd' },
        { token: 'string', foreground: '98c379' },
        { token: 'string.escape', foreground: '56b6c2' },
        { token: 'number', foreground: 'd19a66' },
        { token: 'number.hex', foreground: 'd19a66' },
        { token: 'number.float', foreground: 'd19a66' },
        { token: 'class.name', foreground: 'e5c07b' },
        { token: 'type.class', foreground: 'e5c07b' },
        { token: 'type.identifier', foreground: 'e5c07b' },
        { token: 'type', foreground: 'e5c07b' },
        { token: 'identifier', foreground: 'e06c75' },
        { token: 'variable', foreground: 'e06c75' },
        { token: 'variable.parameter', foreground: 'd19a66' },
        { token: 'function', foreground: '61afef' },
        { token: 'member', foreground: 'e06c75' },
        { token: 'property', foreground: 'e06c75' },
        { token: 'constant', foreground: 'd19a66' },
        { token: 'tag', foreground: 'e06c75' },
        { token: 'attribute.name', foreground: 'd19a66' },
        { token: 'attribute.value', foreground: '98c379' },
        { token: 'operator', foreground: '56b6c2' },
        { token: 'regexp', foreground: '56b6c2' },
        { token: 'annotation', foreground: 'd19a66' }
    ],
    colors: {
        'editor.background': '#282c34',
        'editor.foreground': '#abb2bf',
        'editor.lineHighlightBackground': '#2c313c',
        'editor.selectionBackground': '#3e4451',
        'editorCursor.foreground': '#528bff',
        'editorWhitespace.foreground': '#3b4048',
        'editorIndentGuide.background': '#3b4048',
        'editorIndentGuide.activeBackground': '#c678dd',
        'editorLineNumber.foreground': '#495162',
        'editorLineNumber.activeForeground': '#abb2bf',
        'editorBracketMatch.background': '#3b4048',
        'editorBracketMatch.border': '#528bff',
        'editorWidget.background': '#21252b',
        'editorWidget.border': '#181a1f',
        'editorSuggestWidget.background': '#21252b',
        'editorSuggestWidget.border': '#181a1f',
        'editorSuggestWidget.selectedBackground': '#2c313c',
        'editorError.foreground': '#e06c75',
        'editorWarning.foreground': '#d19a66',
        'editorInfo.foreground': '#56b6c2',
        'editorGutter.background': '#282c34',
        'editorGutter.addedBackground': '#98c379',
        'editorGutter.modifiedBackground': '#e5c07b',
        'editorGutter.deletedBackground': '#e06c75'
    }
};
